version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:8.6.2
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx4g"
      - "network.host:0.0.0.0"
      - ELASTIC_PASSWORD=Abc123...
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - dockernet
  kibana:
    image: kibana:8.6.2
    volumes:
      - kibana-data:/usr/share/kibana/
    ports:
      - '5601:5601'
    networks:
      - dockernet

networks:
  dockernet:
    driver: bridge

volumes:
  es-data:
    driver: local
  kibana-data:
    driver: local
