version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:8.6.2
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ports:
      - '9200:9200'
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx4g"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - dockernet
  kibana:
    image: kibana:8.6.2
    volumes:
      - kibana-data:/usr/share/kibana/
    ports:
      - '5601:5601'
    networks:
      - dockernet

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.2
    volumes:
      - filebeat-data:/usr/share/filebeat/data
      - "C:/Users/Stiafen Flepp/Documents/FHGR/2-Metadata/dblp.xml/data-dblp.xml:/usr/share/filebeat/data-dblp.xml"
      - "./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
    networks:
      - dockernet
    command: filebeat -e -strict.perms=false

networks:
  dockernet:
    driver: bridge

volumes:
  es-data:
    driver: local
  kibana-data:
    driver: local
  filebeat-data:
    driver: local
